---
- name: OS initial Setting
  hosts: 
  become: true
  become_method: sudo
  gather_facts: true


  - include_role:
      name: os_setting
      tasks_from: user.yml

  - include_role:
      name: os_setting
      tasks_from: extra.yml



