- name: firebeat package rsync
  synchronize:
    src: "rsync://{{ setup_ip }}/config/filebeat/filebeat-7.16.1-x86_64.rpm" 
    dest: "/root/"
    mode: pull
    checksum: yes

- name: filebeat install 
  yum: 
    name: "/root/filebeat-7.16.1-x86_64.rpm"
    state: present

- name: filebeat config rsync
  synchronize:
    src: "rsync://{{ setup_ip }}/config/filebeat/filebeat.yml"
    dest: "/etc/filebeat/filebeat.yml"
    mode: pull
    checksum: yes
  
- name: filebeat restart
  service: 
    name: filebeat
    state: restarted 
    enabled: yes
