- name: HASP setting
  import_tasks: hasp.yml

- name: Proftpd setting
  import_tasks: proftpd.yml
  
- name: rsnapshot setting
  import_tasks: rsnapshot.yml

- name: sendmail setting
  import_tasks: sendmail.yml

- name: firewall setting
  import_tasks: firewall.yml

- name: filebeat setting
  import_tasks: filebeat.yml

- name: certbot setting
  import_tasks: certbot.yml

- name: zabbix-agent setting
  import_tasks: zabbit.yml

