- name: proftpd install rsync
  synchronize: 
    src: "rsync://{{ setup_ip }}/app/proftpd-1.3.7a.tar.gz" 
    dest: "/usr/local/src/"
    mode: pull
    checksum: yes

- name: proftpd PAM rsync
  synchronize:
    src: "rsync://{{ setup_ip }}/config/pam_proftpd"
    dest: "/etc/pam.d/proftpd"
    mode: pull
    checksum: yes

- name: proftpd unarchive
  unarchive:
    src: "/usr/local/src/proftpd-1.3.7a.tar.gz"
    dest: "/usr/local/src/"
    remote_src: yes

- name: proftpd configure
  command: >
    ./configure -prefix=/usr/local/proftpd
                --sysconfdir=/etc/proftpd
                --mandir=/usr/share/man
                --enable-dso --enable-nls
                --enable-openssl --enable-authshadow
                --enable-shadow --enable-ctrls
                --with-modules=mod_tls
  args:
    chdir: "/usr/local/src/proftpd-1.3.7a"
  register: configure_result
 
- name: proftpd make & make install
  command: make && make install
  args:
    chdir: "/usr/local/src/proftpd-1.3.7a"
  when: configure_result.rc == 0

- name: proftpd config rsync
  synchronize:
    src: "rsync://{{ setup_ip }}/config/proftpd/"
    dest: "/etc/proftpd/"
  mode: pull
  checksum: yes

- name: proftpd init_script rsync
  synchronize:
    src: "rsync://{{ setup_ip }}/config/centos7/init.proftpd"
    dest: "/etc/init.d/proftpd"
    mode: pull
    checksum: yes

- name: create symbolic 
  file: 
    src: "/etc/init.d/proftpd"
    dest: "/etc/rc3.d/S85proftpd"
    state: link

- name: create log file
  file: 
    path: /web_log/ftp_log
    state: directory
    owner: root
    group: root

- name: create ftpusers file
  file: 
    path: /etc/ftpusers
    state: touch
    owner: root
    group: root

- name: add ftpusers 
  lineinfile:
    path: /etc/ftpusers
    line: "root"
    create: yes

- name: proftpd start
  service:
    name: proftpd
    state: started
    enabled: yes
