- name: HASP 설치
  shell: | 
    rsync -a {{ SETUP }}::set/config/hasp/ /usr/local/hasp/

- name: pipenv 설치
  pip:
    name: pipenv
    version: 2022.4.8
    executable: pip3

- name: pipenv 가상환경 생성 및 패키지 설치
  shell: |
    pipenv --python 3.6
    pipenv install 
  args:
    chdir: /usr/local/hasp
  environment:
    PIPENV_VENV_IN_PROJECT: "true"

- name: HASP 시작
  shell: |
    ./haspd start
  args:
    chdir: /usr/local/hasp 
