- name: php_imagick 설치
  block:
    - name: 설치파일 rsync
      shell: | 
        rsync -a {{ SETUP }}::set/config/upgrade/imagick-3.7.0.tgz {{ SRC }}/
    
    - name: 압축해제
      unarchive:
        src: "{{ SRC }}/imagick-3.7.0.tgz"
        dest: "{{ SRC }}/"
        remote_src: yes
    
    - name: configure 빌드
      shell: | 
        /usr/local/php/bin/phpize
        ./configure --with-php-config=/usr/local/php/bin/php-config
      args:
        chdir: "{{ SRC }}/imagick-3.7.0"
      register: configure_result
      ignore_errors: false 
 
    - name: make & make install 
      shell: | 
        make -j 4 && make install 
      args:
        chdir: "{{ SRC }}/imagick-3.7.0"
      when: configure_result.rc == 0 


 
    
