---
packages:
  - bind-utils
  - ntsysv
  - quota
  - wget
  - rsync
  - lsof
  - gcc
  - gcc-c++
  - gd-devel
  - libjpeg-devel
  - libpng-devel
  - freetype-devel
  - vim 
  - openssl-devel
  - ncurses-devel
  - pam-devel
  - xinetd
  - autoconf
  - sysstat
  - sendmail
  - mailx
  - bc
  - hdparm
  - dnsmasq
  - smartontools
  - psmisc
  - iptables-services
  - bzip2
  - glibc.i686 
  - pcre-devel
  - apr-devel
  - curl-devel
  - libxml2-devel
  - cmake
  - make
  - expat-devel
  - rsyslog
  - tar
  - libtirpc-devel
  - logrotate
  - chrony
  - rpcgen 
  - re2c
  - lynx
  - libtool-ltdl-devel
  - patch
  - convmv
  - libtool
  - yajlyajl-devel
  - python3
  - zstd
  - git 
  - epel-release
  - clamav
  - clamav-update
  - GeoIP-devel
  - rsnapshot
  - htop
  - libmcrypt-devel
  - ImageMagick
  - ImageMagick-devel
